version: '2'
services:
    rollerland-app:
        image: rollerland
        external_links:
            - rollerland-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/rollerland
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rollerland-postgresql:
        extends:
            file: postgresql.yml
            service: rollerland-postgresql
